version: "3.9"

services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - LIBPOSTAL_URL=http://libpostal:5000/parse
    depends_on:
      - libpostal

  api-dev:
    profiles: ["dev"]
    build:
      context: .
      target: dev
    ports:
      - "3001:3000"
    environment:
      - LIBPOSTAL_URL=http://libpostal:5000/parse
    volumes:
      - ./address_validator:/app/address_validator
    depends_on:
      - libpostal

  libpostal:
    build:
      context: .
      dockerfile: Dockerfile.libpostal
    volumes:
      - ./scripts/parse_srv.py:/app/parse_srv.py 